# src/main/resources/application-dev.yml (nếu bạn dùng YAML)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
