server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shopmypham?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.shopmypham: DEBUG
